import type { Metadata } from "next";
import { Doto, Space_Mono, Syne } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import SmoothScroll from "./components/SmoothScroll";

const doto = Doto({
  subsets: ["latin"],
  variable: "--font-doto",
  weight: ["800"],
  display: "block",
  preload: true,
});

const spaceMono = Space_Mono({
  subsets: ["latin"],
  variable: "--font-space-mono",
  weight: ["400", "700"],
  display: "block",
  preload: true,
});

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
  weight: ["400", "500", "600", '700','800'],
  display: "block",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${doto.variable} ${spaceMono.variable} ${syne.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
        <SmoothScroll>
        <main className="relative z-30 bg-white">
        {children}
        </main>
        </SmoothScroll>
        </body>
    </html>
  );
}
